# theme-config.yaml

theme:
  name: "MyCustomTheme"
  font-size: 16px
  background-color: "#ffffff"
  text-color: "#333333"
  border-color: "#0099cc"  # สีขอบที่คุณต้องการ
  border-width: 2px        # ความกว้างของขอบ

# คุณยังสามารถกำหนดค่าอื่น ๆ ตามที่คุณต้องการ
